name: Deploy Frontend
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (only if package.json exists)
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (only if package.json exists)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Build (no-op if no build script)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json >/dev/null; then
            npm run build
          else
            echo "No build step"
          fi
        shell: bash

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 "${{ secrets.HOSTINGER2 }}" >> ~/.ssh/known_hosts

      - name: Rsync to server
        run: |
          SRC="."
          if [ -d "dist" ]; then SRC="dist"; fi
          rsync -az --delete -e "ssh -p 22 -i ~/.ssh/id_rsa" "$SRC/" "root@${{ secrets.HOSTINGER2 }}:${{ secrets.DEPLOY_PATH }}/"
