name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/setup-playwright@v1
      - run: npm ci
        working-directory: apps/frontend
      - run: npx playwright test
        working-directory: apps/frontend
        env:
          NEXT_PUBLIC_DRONEREGION_URL: ${{ secrets.NEXT_PUBLIC_DRONEREGION_URL }}
